export type OperationTypeApi = "income" | "outcome";
export type CategoryApi =
  | "suppliers"
  | "sales"
  | "operational"
  | "administrative"
  | "others";
export type BusinessTypeApi = "B2B" | "B2C";
export type ApiDateString = string;

// /api/metrics/facets item fields used as date-range and filter references.
export interface FacetsResponse {
  /** Allowed values for the operation_type query parameter. */
  operation_types: OperationTypeApi[];
  /** Allowed values for the business_type query parameter. */
  business_types: BusinessTypeApi[];
  /** Allowed values for the category query parameter. */
  categories: CategoryApi[];
  /** Earliest date available in the dataset (OpenAPI format: date). */
  min_date: ApiDateString;
  /** Latest date available in the dataset (OpenAPI format: date). */
  max_date: ApiDateString;
}

// Date-range reference extracted from /api/metrics/facets.
export interface DateRangeReference {
  /** Earliest allowed date boundary (OpenAPI format: date). */
  min_date: ApiDateString;
  /** Latest allowed date boundary (OpenAPI format: date). */
  max_date: ApiDateString;
}

// B2B vs B2C selector reference extracted from /api/metrics/facets.
export interface BusinessTypeReference {
  /** Business segments supported by the API. */
  business_types: BusinessTypeApi[];
}

export interface AlertEntry {
  /** Period label generated by API aggregation (group_by). */
  period: string;
  /** Total outcome observed in the alert period. */
  outcome_total: number;
  /** Baseline outcome average used for anomaly comparison. */
  baseline_average: number;
  /** Relative increase ratio vs baseline (for example 0.35 = +35%). */
  increase_ratio: number;
}

export type AlertsResponse = AlertEntry[];

export interface CategoryEntry {
  /** Category name returned by /api/metrics/categories/top. */
  category: CategoryApi;
  /** Operation type used for category aggregation. */
  operation_type: OperationTypeApi;
  /** Aggregated amount for the category row. */
  total_amount: number;
}

export type TopCategoriesResponse = CategoryEntry[];
